require('dotenv').config();

exports.envConstants = {
  DB_HOST: process.env.DB_HOST,
  DB_PORT: process.env.DB_PORT,
  DB_NAME: process.env.DB_NAME,
  DB_PASS: process.env.DB_PASS,
  DB_USER: process.env.DB_USER,
  DB_DIALECT: process.env.DB_DIALECT || 'mongodb',
  DB_DEBUG_MODE: process.env.DB_DEBUG_MODE || 'true',
  APP_HOST: process.env.APP_HOST || 'localhost',
  APP_PORT: process.env.APP_PORT || 4000,
  SECRET: process.env.SECRET || 'PHRANKLIN',
  NODE_ENV: process.env.NODE_ENV || 'dev',
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || 'ABCDEFGHIJKLMNOPQRSTUVWXYZ123456',
  AUTHENTICATION: process.env.AUTHENTICATION || 'false',
  REDIS_SERVER: process.env.REDIS_SERVER || 'false',
  FRONT_END_URL: process.env.FRONT_END_URL || 'http://localhost:3000',
  JWT_TOKEN_EXPIRATION_TIME: process.env.JWT_TOKEN_EXPIRATION_TIME || '7d',
  SSL_CERT_PATH: process.env.SSL_CERT_PATH,
  SSL_KEY_PATH: process.env.SSL_KEY_PATH,
  URL:process.env.url,
  S3_ACCESS: process.env.S3_ACCESS,
  S3_SECRET: process.env.S3_SECRET,
  BUCKET_NAME: process.env.S3_BUCKET,
  ACCESS_TOKEN: process.env.HUBSPOT_APP_ID,
  CLIENT_ID: process.env.CLIENT_ID,
  CLIENT_SECRET: process.env.CLIENT_SECRET,
  REDIRECT_URL: process.env.REDIRECT_URL,
  APP_ID:process.env.APP_ID,
  WEBHOOK_URL:process.env.WEBHOOK_URL,
  DEVELOPER_API_KEY:process.env.DEVELOPER_API_KEY,
  websiteUrl: process.env.FRONT_END_URL,
  SES_KEY: process.env.AWS_SES_KEY,
  SES_SECRET: process.env.AWS_SES_SECRET,
  SES_HOST: process.env.AWS_SES_HOST,
  SES_REGION: process.env.AWS_SES_REGION,
  SES_VERIFIED_MAIL: process.env.SES_VERIFIED_MAIL,
  GEOCODING_API: process.env.GEOCODING_KEY
};
